### ISSUE TITLE
This repo isn't receiving the latest updates from the Python templates

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/document-ai-samples#130]
The problem is Owl Bot doesn't have permission to push to branches in this repo:
```
git push  origin owl-bot-update-lock-1f0dbd02745fb7cf255563dab5968345989308544e52b7f460deadd5e78e63b0
remote: Permission to GoogleCloudPlatform/document-ai-samples.git denied to gcf-owl-bot[bot].
```

If you no longer want Owl Bot to automatically copy templates into this repo, please remove `.github/.OwlBot*` and `owlbot.py`.  Otherwise, please grant gcf-owl-bot the necessary permissions.

CC @parthea

**Comment by holtskinner** [comment]
Granted Permission to gcf-owl-bot
