### ISSUE TITLE
[docai-warehouse]  DocumentAI Processors not working while loading document

### ISSUE THREAD

**Issue by RennerBSL** [GoogleCloudPlatform/document-ai-samples#162]
Hey all, just followed the "Using Document AI Warehouse to Ingest, Process, and Search Documents” codelab step-by-step. Now I can successfully load documents, however, once I try to use any document AI processor with it, the document breaks, with no response from the processor as well.

![image](https://user-images.githubusercontent.com/113723197/198394854-198d49d2-efdc-4435-b8a7-4927fdcb1fba.png)

Thanks for your attention.

**Comment by kolban-google** [comment]
There was a problem just following the release of this new service which has now been resolved.  Can we try it again as of today ... my hope/understanding is that the issue you describe will be gone.  I too saw this exact issue and it "resolved itself" sometime in early December 2022.

**Comment by holtskinner** [comment]
From https://cloud.google.com/document-warehouse/docs/release-notes#January_16_2024

> Document AI Warehouse is deprecated and will no longer be available on Google Cloud after January 16, 2025. To safeguard your data, migrate any documents currently saved in Document AI Warehouse to an alternative like Cloud Storage. Ensure that your data migration is completed before the out of service date to prevent any data loss. See [Deprecations](https://cloud.google.com/document-warehouse/docs/deprecations/index) for details.
