### ISSUE TITLE
[DocAI-Warehouse] Can't get documents via REST API

### ISSUE THREAD

**Issue by RennerBSL** [GoogleCloudPlatform/document-ai-samples#169]
Hello.

I'm trying to get the documents (and its properties) I uploaded into DocAI Warehouse with the REST API. I can get the document's schemas all right, but when I try to get the documents itself using the following request: 

GET https://contentwarehouse.googleapis.com/v1/projects/PROJECT_NUMBER/locations/LOCATION/documents/DOCUMENT_ID 

The document is not found.

![image](https://user-images.githubusercontent.com/113723197/200633891-8b01ee6d-f8ac-49fa-bd2a-5cdcbb025f41.png)

Also, when just passing the document's path, without specifying any ID, it is denied, but all my credentials and authorizations are set up just right: 

![image](https://user-images.githubusercontent.com/113723197/200634396-1de3f460-2439-4689-bb76-2c0bc6acca2e.png)

I was wondering if the calling document's path is correct or if there is still some restriction in accessing it. If that's the case, the permission “contentwarehouse.documents.list” is not listed in any of the roles available for the DocAI Warehouse. 

Thank you.

**Comment by kolban-google** [comment]
Reviewing the REST API documentation for getting a document found here ...

https://cloud.google.com/document-warehouse/docs/reference/rest/v1/projects.locations.documents/get

I don't see a match to the format for your request.  In your example, you are doing a GET request to:

```
https://contentwarehouse.googleapis.com/v1/projects/PROJECT_NUMBER/locations/LOCATION/documents/DOCUMENT_ID
```

whereas when I look at the docs, it seems to require a POST request to the URL:

```
https://contentwarehouse.googleapis.com/v1/projects/PROJECT_NUMBER/locations/LOCATION/documents/DOCUMENT_ID:get
```

Note the different method (`POST` vs `GET`) and the addition of `:get` as part of the URL path.
