### ISSUE TITLE
[docai-warehouse]

### ISSUE THREAD

**Issue by SONIBHAVAN** [GoogleCloudPlatform/document-ai-samples#291]
"the Document AI Warehouse console located at https://documentwarehouse.cloud.google.com/ (which is external to the Google Cloud console)."
The link is not working (giving 404) can someone help out

**Comment by holtskinner** [comment]
This is currently a known issue. The UI has been taken down temporarily for maintenance. It should be back on Monday, Jan 30. The API is still active.

**Comment by holtskinner** [comment]
The issue has been resolved and the UI is back up.
