### ISSUE TITLE
Handling nested labels with CDE 

### ISSUE THREAD

**Issue by evekhm** [GoogleCloudPlatform/document-ai-samples#304]
Hello,

I am looking into using bq-connector. I ran a small test to get data into BigQuery and have a question about the format raw_entities are stored in BigQuery.
1)  I am having difficulty querying data the way it is dumped as-is into BigQuery.  How can I get a list of all "issuerName"?
 
2) On nested Labels (with CDE), it also seems to break (see example below)

raw_entities 
```
[
    {"name": "Issuer", "value": "blueshieldca.com/promise", "confidence": 0.9994744658470154, "page_number": 1,
    "children":
      [
        [
            {"name": "issurerName", "value": "blueshieldca.com/promise", "confidence": 0.9994744658470154, "page_number": 1}
         ],
        [
          {"name": "routineFax", "value": "123", "confidence": 0.989255428314209, "page_number": 1},
          {"name": "modificationFax", "value": "123", "confidence": 0.9957648515701294, "page_number": 1},
          {"name": "retroFax", "value": "123", "confidence": 0.996335506439209, "page_number": 1},
          {"name": "urgentFax", "value": "123", "confidence": 0.8285958170890808, "page_number": 1}
        ]
      ]},
 ]
```

Instead I expect something like this (a Valid JSON):
```
[
  {"name": "Issuer", "value": "blueshieldca.com/promise", "confidence": 0.9994744658470154, "page_number": 1, 
  "children": 
    [ 
       {"name": "issurerName", "value": "blueshieldca.com/promise", "confidence": 0.9994744658470154, "page_number": 1}, 
       {"name": "routineFax", "value": "123", "confidence": 0.989255428314209, "page_number": 1}, 
       {"name": "modificationFax", "value": "123", "confidence": 0.9957648515701294, "page_number": 1},
       {"name": "retroFax", "value": "123", "confidence": 0.996335506439209, "page_number": 1}, 
       {"name": "urgentFax", "value": "123", "confidence": 0.8285958170890808, "page_number": 1}
    ]
  }
]
```

The way CDE has Labels Schema Defined (with Child Labels): 

```
Issuer |  
  -  issurerName | Plain text | Required once |   | Yes |   |   |   |  
  -  modificationFax | Plain text | Required once |   | Yes |   |   |   |  
  -  retroFax | Plain text | Required once |   | Yes |   |   |   |  
  -  routineFax | Plain text | Required once |   | Yes |   |   |   |  
  -  urgentFax | Plain text | Required once.  | Yes |   |   |   |  
```

Response from the Parser:

**Comment by mservidio** [comment]
Hi @evekhm - Regarding the JSON, you're seeing it as a string in BQ? I just checked the code and it looks like it's set as a json object in python using:

row["raw_entities"] = json.dumps(self.to_raw_entities())

For the nested labels, I've not been able to test it with too many  processors, so it's very possible the nesting/recursion logic could be a little buggy.

**Comment by evekhm** [comment]
You are right about  json.dumps (was updating my question when you already posted an answer!)
However I reformulated it: If anybody has examples of Queries that could properly extract data from the nested json lists?
As in my example.

Regarding nested labels, debugging as we speak to provide more details.

**Comment by mservidio** [comment]
I haven't played with the JSON data type in BQ very much, but check out the functions here: https://cloud.google.com/bigquery/docs/reference/standard-sql/json_functions

**Comment by evekhm** [comment]
What would help, is making raw_entities JSON vs STRING.
If the field is not created up-front, then it is added on the fly as a STRING.

We could either change creation, or add recommendation of setting it up front as JSON.
What do you think?

**Comment by evekhm** [comment]
Regarding nested_labels, there is a bug with BqDocumentMapper.py._parse_entities (or maybe wrong assumption on document.entities structure)
When going over the list of entities and adding children to parent, following goes wrong.
Imagine a parent label with 5 children, however in the document.entities those are coming in portions:

1) First comes parent with entity.properties with just one child label => Creates parent with a child (Label 1)
2) Again comes parent with entity.properties having 4 labels in entity.properties => Creates a row with 4 fields and instead of extending previously created list of 1 child Label1, appends a row.

Structure we need:
parent_field-> children  row-> fields: [Label1, Label2, Label3, Label4]

Instead we are getting:
 parent_field-> children  row1: fields:[Label1] , row2: fields:[Label2, Label3, Label4]

And this results in the wrong JSON sent to BigQuery. 

CDE has following structure:
parent_label:
- Label1
- Label2
- Label3
- Label4

I have the data handy if needed to reproduce while debugging.

**Comment by mservidio** [comment]
I think this may be a situation where the nesting structure could differ based on the processor. The part that's much different is the [0], which I don't think would work for the prior tested files that I used to write the original nesting logic.

I wonder if we need to add this as a parsing methodology type in the arguments to conditionally choose which parsing logic to use.

**Comment by evekhm** [comment]
I could share the document.entities json if that would help for comparison. 
are you sure the change I propose would not work for the tested files with nested structure you created before? Maybe I am not following the [0] example well.

**Comment by evekhm** [comment]
> I think this may be a situation where the nesting structure could differ based on the processor. The part that's much different is the [0], which I don't think would work for the prior tested files that I used to write the original nesting logic.
> 
> I wonder if we need to add this as a parsing methodology type in the arguments to conditionally choose which parsing logic to use.
> 
> @holtskinner will nested structures differ based on processors?

@mservidio could you share an example, when you think new logic would break?

**Comment by mservidio** [comment]
I re-read your earlier diagnosis and I think I understand the situation now. Your fix looks good to me.

**Comment by mservidio** [comment]
@evekhm Are we ok to close this out?
