### ISSUE TITLE
sync vs async processing

### ISSUE THREAD

**Issue by evekhm** [GoogleCloudPlatform/document-ai-samples#308]
I would like to suggest an option to chose between batch processing (which is slow for a singe document) versus process_document request.
Running single file with BatchProcessRequest (_`_process_async`_)  is 2.5-3 times slower than using process_document (`__process_sync_ `- which is not used in code).
For the bq-connector

**Comment by mservidio** [comment]
Good catch this is a bug actually. Line 280 of Processor.py I may have commented out when doing testing a few weeks ago.

The ability to control when sync versus async is used can be done using the max_sync_page_count param/argument.
