### ISSUE TITLE
pix-to-info

### ISSUE THREAD

**Issue by binary42420** [GoogleCloudPlatform/document-ai-samples#605]
how can i display specific entities below the main image output automatically ? 

i understand they appear in the json formatted tree on the doc tab, but how can i display them in raw html text on the screen as soon as a new file is processed?

in other words, how do you call for an entity? whats the syntax in python?
`<script>
document.body.innerHTML = document.body.innerHTML + "Entity Type: " + document.entity.type_ + ".  Entity Text: " + document.entity.text;
</script>`

I know the js syntax is not correct either, but whats the correct way to call specific entities like the rough example above in python?

**Comment by telpirion** [comment]
@binary42420 Hello, I'm afraid that Google Cloud doesn't support any client-side JavaScript libraries. Your best bet is to process the result server-side and then compose the client web page programmatically.
