### ISSUE TITLE
[docai-warehouse] The LOWER() function returns internal error

### ISSUE THREAD

**Issue by snekcz** [GoogleCloudPlatform/document-ai-samples#698]
When I use the `LOWER()` function in `documentQuery.propertyFilter.condition` attribute, when searching for documents, the API always returns `Error: 13 INTERNAL: Internal error encountered.`. 

Here is the code example:
```
const searchRequest = {
    // The full resource name of the location, e.g.:
    // projects/{project_number}/locations/{location}
    parent: `projects/${projectNumber}/locations/${location}`,

    // Document Text Query
    documentQuery: {
        propertyFilter: [
        {
          documentSchemaName: `projects/${projectNumber}/locations/${location}/documentSchemas/2h8xxxxxx`,
          condition: 'LOWER(certificate_company)="cohesity"'
        }
      ],
      fileTypeFilter: {
        fileType: 'DOCUMENT',
      },
    },

    // Histogram Query
    histogramQueries: [
      {
        histogramQuery: 'count("DocumentSchemaId")',
      },
    ],
    requestMetadata: {userInfo: {id: userId}}
  };

  // Make Request
  const response = serviceClient.searchDocuments(searchRequest);
```

**Comment by holtskinner** [comment]
From https://cloud.google.com/document-warehouse/docs/release-notes#January_16_2024

> Document AI Warehouse is deprecated and will no longer be available on Google Cloud after January 16, 2025. To safeguard your data, migrate any documents currently saved in Document AI Warehouse to an alternative like Cloud Storage. Ensure that your data migration is completed before the out of service date to prevent any data loss. See [Deprecations](https://cloud.google.com/document-warehouse/docs/deprecations/index) for details.
