### ISSUE TITLE
Error on import 'documentai'

### ISSUE THREAD

**Issue by tapialuism** [GoogleCloudPlatform/document-ai-samples#706]
_My first time posting let me know what I'm doing wrong. Thanks_

I ran this project fine the first time. The subsequent times have been giving me the same error.
https://codelabs.developers.google.com/codelabs/docai-ocr-python#7

- The docAi processor is enabled
- I'm able to test a single document via the upload.
- I'm unclear about the file_path.

**Error below.**
 
```
Traceback (most recent call last):

 File "/home/xxxxxx/online_processing.py", line 2, in <module>

   from google.cloud import documentai
>ImportError: cannot import name 'documentai' from 'google.cloud' (unknown location)

from google.api_core.client_options import ClientOptions

from google.cloud import documentai
```

My code is the following from the first 13 lines:
**Code Below**

```py
PROJECT_ID = "ai-doc-train-amz"

LOCATION = "us"  # Format is 'us' or 'eu'
PROCESSOR_ID = "6d4e34eae77bd18d"  # Create processor in Cloud Console

# The local file in your current working directory
FILE_PATH = "Winnie_the_Pooh_3_Pages.pdf"
# Refer to https://cloud.google.com/document-ai/docs/file-types
# for supported file types
MIME_TYPE = "application/pdf"
```

**Comment by holtskinner** [comment]
Did you install the Document AI Python Library?

Follow the directions on [Step 6 to install the library](https://codelabs.developers.google.com/codelabs/docai-ocr-python#5)

Then follow the directions in [Step 7 to download the PDF to your local machine](https://codelabs.developers.google.com/codelabs/docai-ocr-python#6)

The `file_path` should be the path to the PDF you downloaded, if you save it to a different directory than the python file you're running, you'll need to provide the full file path.

This page from W3 Schools shows how File Input/Output works in Python.

https://www.w3schools.com/python/python_file_handling.asp
