### ISSUE TITLE
ocr processor sample code doesnt work

### ISSUE THREAD

**Issue by sanjosh** [GoogleCloudPlatform/document-ai-samples#715]
code given here does not work
https://github.com/GoogleCloudPlatform/document-ai-samples/tree/main/pdf-embedded-text

exception thrown 

1. processor_version = "pretrained-ocr-v2.0-2023-06-02" , it says does not support pdf
2. processor_version = "pretrained-ocr-v1.2-2022-11-10"  , it says Premium OCR models and features can only be enabled through OCR 2.0+ processors.
3. processor_version = "pretrained-ocr-v1.1-2022-09-12", it says Premium OCR models and features can only be enabled through OCR 2.0+ processors.

the location is "us"

do you need my ocr processor id

**Comment by holtskinner** [comment]
The issue was that the `ProcessOptions` object had some settings that have since been made Premium OCR Add ons or have changed their process.

See https://cloud.google.com/document-ai/docs/process-documents-ocr
