### ISSUE TITLE
[docai-ocr-python] 6. Install the client library without sudo

### ISSUE THREAD

**Issue by jmtosi** [GoogleCloudPlatform/document-ai-samples#718]
Required `sudo pip install <package name>` for `google-cloud-documentai `and `google-cloud-documentai-toolbox.` This placed the packages in dist-packages as opposed to site-packages. An ImportError was occurring when installed in site-packages.

**Comment by holtskinner** [comment]
Thank you for the feedback, the codelab https://codelabs.developers.google.com/codelabs/docai-ocr-python intentionally doesn't install using `sudo` to avoid elevated permissions.

It's also possible the imports were failing due to the python versions not matching between install and run.
