### ISSUE TITLE
Key-Value pair swapped

### ISSUE THREAD

**Issue by amini2nt** [GoogleCloudPlatform/document-ai-samples#80]
I have tried with documents where the end result leads to having the keys and values swapped wrongly. Is this a common occurrence? Has anyone else dealt with it?

**Comment by ivanmkc** [comment]
Can you provide more context/code?

**Comment by ivanmkc** [comment]
@matthewayne I wonder if it's just a service issue, as in the model isn't 100% accurate.

**Comment by amini2nt** [comment]
Is there a way to finetune the model and/or provide the samples it gets wrong ?

**Comment by matthewayne** [comment]
Closing for now, please reopen or create a new issue with the requested context if you're still having this issue
